rails:
  build: .
  command: >
    bash -c '
    bin/rake db:migrate RAILS_ENV=development &&
    ./bin/rails s -b 0.0.0.0
    '
  environment:
    - VIRTUAL_HOST=myapp.docker # for dinghy
    - HTTPS_METHOD=noredirect # for dinghy
    - SERVER_ENV=development
    - DATABASE_HOST=postgres
    - DATABASE_PASSWORD=dbpass
    - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
    - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    - S3_BUCKET=${S3_BUCKET}
    - REDIS_URL=redis://redis:6379
  volumes:
    - ./:/app
  links:
    - postgres
    - redis

postgres:
  image: postgres:9.5.3
  ports:
    - "5433:5432"
  environment:
    POSTGRES_PASSWORD: dbpass
    POSTGRES_DB: myapp_dev
  volumes:
    - ./sql:/sql

redis:
  image: redis:3.2.1-alpine
  ports:
    - "7113:6379"
