default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *default
  database: myapp_development
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: myapp_test
  port: <%= ENV['DATABASE_PORT'] || 5432 %>

staging:
  <<: *default
  database: myapp_staging

production:
  <<: *default
  database: myapp_production
